version: '3.4'

services:
  datadb:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: datadb
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5

  logsdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logsdb
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5

  finbeat.apis:
    image: ${DOCKER_REGISTRY-}finbeatapis
    build:
      context: .
      dockerfile: FinBeat.APIs/Dockerfile
    depends_on:
      datadb:
        condition: service_healthy
      logsdb:
        condition: service_healthy
    restart: always